services:
  - type: web
    name: moneta
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 